config/routes.rb
Rails.application.routes.draw do
  get '/public_recipes', to:"public_recipes#index"
  resources :recipes
  get '/general_shopping_list', to: "recipes#general_shopping_list"
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root "public_recipes#index"
  resources :recipes, only: [:index, :show, :new, :create] do
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :inventories, only: [:index, :show, :new, :create, :destroy] do
    resources :inventory_foods, only: [:new, :create, :destroy]
  end
  resources :foods, only: [:new, :create, :index, :show, :destroy]
  get '/shopping_list', to: 'shopping_list#index', as: :shopping_list, recipe_id: /[0-9]+/, inventory_id: /[0-9]+/
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods
  has_many :foods, through: :inventory_foods
  validates :name, presence: true
  validates :description, length: { maximum: 250 }
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  def index
    @inventories = current_user.inventories
  end

  def show
    @inventory = Inventory.includes(:inventory_foods).find(params[:id])
  end

  def new
    @inventory = Inventory.new
    respond_to do |format|
      format.html { render :new, locals: { inventory: @inventory } }
    end
  end

  def create
    @inventory = Inventory.new(inventory_params)
    respond_to do |format|
      format.html do
        if @inventory.save
          flash[:sucess] = 'Inventory Saved successfully'
          redirect_to inventories_path
        else
          flash.now[:error] = 'Error: Inventory could not be saved'
          render { render :new, locals: { inventory: @inventory } }
        end
      end
    end
  end

  def destroy
    Inventory.destroy(params[:id])
    redirect_to inventories_path
  end

  private

  def inventory_params
    params.require(:inventory).permit(:name, :description).merge(user: current_user)
  end
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/views/inventories/index.html.erb
<section>
  <div class="container">
    <%= render partial: 'shared/inventory', collection: @inventories %>
    <%= link_to 'Create New Inventory', new_inventory_path, class: "btn btn-success mt-5"%>
  </div>
<section>

app/views/inventories/new.html.erb
<div class="container">
  <h1>Create new Inventory</h1>
  <%= bootstrap_form_with model: inventory do |f| %>
    <%= f.text_field :name %>
    <%= f.text_area :description %>
    <%= f.submit %>
  <% end %>
</div>

app/views/inventories/show.html.erb
<section>
  <div class="container">
    <div class="d-flex flex-column pb-3 mb-5 border-bottom">
      <h1 class="m-auto"><%= @inventory.name %></h1>
      <%= link_to 'Add food', new_inventory_inventory_food_path(@inventory), class: 'btn btn-success d-block ms-auto' %>
    </div>
  <table class="table table-bordered table-striped w-75 m-auto ">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @inventory.inventory_foods.each do |inventory_food| %>
        <tr>
          <td><%= inventory_food.food.name %></td>
          <td><%= inventory_food.quantity %></td>
          <td><%= button_to 'Delete', inventory_inventory_food_path(@inventory, id: inventory_food), method: :delete, data: { turbo: false }, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
</section>