config/routes.rb
Rails.application.routes.draw do
  get '/public_recipes', to:"public_recipes#index"
  resources :recipes
  get '/general_shopping_list', to: "recipes#general_shopping_list"
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root "public_recipes#index"
  resources :recipes, only: [:index, :show, :new, :create] do
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :inventories, only: [:index, :show, :new, :create, :destroy] do
    resources :inventory_foods, only: [:new, :create, :destroy]
  end
  resources :foods, only: [:new, :create, :index, :show, :destroy]
  get '/shopping_list', to: 'shopping_list#index', as: :shopping_list, recipe_id: /[0-9]+/, inventory_id: /[0-9]+/
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, :preparation_time, :cooking_time, :description, presence: true
  belongs_to :user, foreign_key: 'user_id'
  has_many :recipe_foods, dependent: :destroy
  has_many :food, through: :recipe_foods
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = current_user.recipes
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods

    @inventory_data = Inventory.all
    return if params[:inventory_id].nil?

    recipe_food_list = RecipeFood.where(recipe_id: params[:id] || params[:recipe_id]).pluck(:food_id)
    @if_foods_list = InventoryFood.where(inventory_id: params[:inventory_id]).pluck(:food_id)
    @inventory = Inventory.find(params[:inventory_id])
    diff = recipe_food_list - @if_foods_list
    @meta_data = Food.where(id: diff).pluck(:id, :name, :measurement_unit, :price)
    @total_price = 0
    @meta_data.each do |item|
      @total_price += RecipeFood.find_by(food_id: item[0]).quantity * item[3]
    end
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    respond_to do |format|
      format.html { render :new, locals: { recipe: @render } }
    end
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def shopping_list
    @recipe_shopping = Recipe.find(params[:id]).recipe_foods
    @food = []
    @recipe_shopping.ids.each do |_id|
      @food.push(Food.find_by(:id))
    end
    @user_food = current_user.foodss
    @comparison_food = custom_difference(@food, @user_food)
    @food.each do |a|
      puts a.name
    end
    puts 'hello'
    @user_food.each do |a|
      puts a.name
    end
    same_food_result = same_food(@food, @user_food)
    if same_food_result.zero?
      @comparison_food
    else
      @comparison_food.append(same_food(@food, @user_food))
    end
  end

  def new_ingredient
    @recipe = Recipe.find(params[:id])
    @recipe_food = @recipe.recipe_foods.build
    @ingredient = RecipeFood.create(recipe_id: params[:recipe_id], food_id: params[:food_id],
                                    quantity: params[:quantity])

    if @ingredient.save
      flash[:notice] = 'Ingredient was successfully created.'
      redirect_to recipe_url(params[:recipe_id])
    else
      flash[:alert] = 'Ingredient was not created.'
      render :new_ingredient
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description,
                                   :public).merge(user_id: current_user.id)
  end

  def same_food(_food, _user_food)
    @comparis_food = []
    @user_food.each do |uf|
      @food.each do |rf|
        next unless uf.name == rf.name
        next if (uf.quantity - rf.quantity).zero?

        uf.quantity = uf.quantity - rf.quantity
        @comparis_food.push(uf)
      end
    end
    if @comparis_food.count.zero?
      0
    else
      @comparis_food
    end
  end

  def custom_difference(all, subset)
    all.select do |all_curr|
      subset.find do |subset_curr|
        subset_curr.name == all_curr.name
      end.nil?
    end
  end
end

app/views/recipes/_form.html.erb
<%= bootstrap_form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :name %>
  <%= form.label :preparation_time, style: "display: block" %>
  <%= form.number_field :preparation_time %>
  <%= form.label :cooking_time, style: "display: block" %>
  <%= form.number_field :cooking_time %>
  <%= form.text_area :description %>
  <%= form.select :public, options_for_select([["True", true], ["False", false]]), class:"block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500" %>
  <%= form.submit %>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="d-flex align-items-center h-100 bg-dark border rounded">
  <div class="col-4 p-2 border-right border-gray text-white text-lg">
    <!-- content for the first part goes here -->
    <h1><%= recipe.name %></h1>
    <% if can? :destroy, recipe %>
      <%= button_to "Delete", recipe , method: :delete, class:"bg-blue-500 h font-bold py-2 px-4 rounded" %>
    <% end %>
  </div>
  <div class="col-8 p-2">
    <!-- content for the second part goes here -->
    <div class="text-white">
      <p><%= recipe.description %></p>
    </div>
  </div>
</div

app/views/recipes/edit.html.erb
<div class="container">
  <h1>Editing recipe</h1>

  <%= render "form", recipe: @recipe %>

  <br>

  <div>
    <%= link_to "Show this recipe", @recipe %> |
    <%= link_to "Back to recipes", recipes_path %>
  </div>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>


<div class="recipe-list container">
  <div>
    <%= link_to "New Recipe", new_recipe_path, class:"link-primary" %>
  </div>
  <ul class="border-2 border-gray-600">
    <% if @recipes&.empty? %>
      <p>No recipes to show!</p>
      <%else%>
      <% @recipes&.each do |recipe| %>
        <%= render recipe %>
         <p>
          <%= link_to "Show this recipe", recipe, class:"link-primary" %>
        </p>
      <% end %>
    <%end%>
  </ul>
</div>

app/views/recipes/new.html.erb
<div class="container">

  <h1>New recipe</h1>

  <%= render "form", recipe: @recipe %>

  <br>

  <div>
    <%= link_to "Back to recipes", recipes_path %>
  </div>
</div>

app/views/recipes/public_recipes.html.erb
<div class="container">
  <h1>Public Recipes</h1>
  <%= @public_recipes.each do |public_recipe|%>
  <table class="table table-borderless">
    <tr class="row">
      <td><%= public_recipe.name%></td>
      <td><%= public_recipe.description %></td>
    </tr>
    <tr class="row">
      <td>By <%= public_recipe.user %></td>      
    </tr>
  </table>
</div>

app/views/recipes/shopping_list.html.erb
<div class="shopping_list_container">
  <h1>Shopping List</h1>
  <h4>Amount of food items to buy: <%= @comparison_food.count %>  Total value of food needed: 
    <% sum = 0 %>
    <% @comparison_food.each do |cf| %>
      <% sum += cf.quantity * cf.price %>
    <% end %>
    <%= sum %>
  <h4>
  
  <br />
  <% if @comparison_food.count == 0 %>
    <p>You have all the ingredients</p>
  <% else %>
    <table>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Price</th>
      </tr>
      <% @comparison_food.each do |f| %>
      <tr>
        <td><%= f.name %></td>
        <td><%= f.quantity %> <%= f.measurement_unit %></td>
        <td><%= f.price %></td>
      </tr>
      <% end %>
    </table>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="container">
<p style="color: green"><%= notice %></p>
<div class="d-flex justify-content-between">
  <div class="left">
    <ul id="<%= dom_id @recipe %>" class="list-group">
      <li class="list-group-item">
        <strong>Name:</strong>
        <%= @recipe.name %>
      </li>

      <li class="list-group-item">
        <strong>Preparation time:</strong>
        <%= @recipe.preparation_time %>
      </li>

      <li class="list-group-item">
        <strong>Cooking time:</strong>
        <%= @recipe.cooking_time %>
      </li>

      <li class="list-group-item">
        <strong>Description:</strong>
        <%= @recipe.description %>
      </li>

    </ul>
  </div>
  <div class="right">
    <div>
      <label>Public</label>
      <label class="switch">
        <input type="checkbox">
        <span class="slider round"></span>
      </label>
    </div>
   <li class="list-group-item">
        <strong>Public:</strong>
        <%= @recipe.public %>
    </li>
  </div>
</div>
<div class="container mx-auto mt-28 px-5 ">

  <%= link_to "Back to recipes", recipes_path, class:"no-underline hover:underline text-purple-700 text-lg"%>
  <div class="d-flex justify-content-between">
    <button type="button" class="long-btn" data-bs-toggle="modal" data-bs-target="#shoppingModal">Generate Shopping List</button>
    <%= link_to "Add Ingredients", new_recipe_recipe_food_path(@recipe), class:"no-underline hover:underline text-purple-700 text-lg"%>
  </div>
<table class="table table-striped table-dark">
  <thead>
    <tr class="divide-x">
      <th class="flex align-left pl-1">Food</th>
      <th class="ml-0">Quantity</th>
      <th class="flex pl-1">Value</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @recipe_foods.each do |recipe_food| %>
     <tr
      key={mission.mission_id}
      class="odd:bg-gray-200 divide-x divide-gray-300"
    >
      <td class="flex align-top m-auto"><%= recipe_food.food.name %></td>
      <td class="px-3 py-2"><%= recipe_food.quantity %></td>
      <td><%= @price %></td>
      <td>
          <div class="status w-64 flex justify-around text-xs">
            <span class="badge bg-blue-400 text-white rounded-sm px-1 py-0.5 uppercase grid place-items-center">
              <%= link_to "Edit this recipe", edit_recipe_recipe_food_path(@recipe, recipe_food), class: "btn btn-primary" %>
            </span>
          </div>
      </td>
      <td>
          <div class="w-64 flex justify-around text-xs text-sm text-red-600 border-red-400 rounded-sm border-2 px-1 py-0.5">
          <%= button_to 'Delete', recipe_recipe_food_path(@recipe, id: recipe_food), method: :delete, data: { turbo: false }, class: 'btn btn-danger' %>
          </div>

      </td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>
<%= render "layouts/shopping_list" %>

<!-- Modal -->
<div class="modal fade" id="shoppingModal" tabindex="-1" aria-labelledby="shoppingModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="shoppingModalLabel">Shopping</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <h3 style="text-align: center">Generating Shopping List</h3>
        <p>Choose an inventory to use</p>
        <div class="inventory-choose">
          <select class="form-select" aria-label="Default select example" style="width: 50%" id="invetory_list">
            <option selected>Select Inventory</option>
            <% @inventory_data.each do |item| %>
              <option value=<%= item.id %>><%= item.name %></option>
            <% end %>
          </select>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="generate" onclick="window.location.href = '/shopping_list?recipe_id=<%= @recipe.id %>&inventory_id='+document.getElementById('invetory_list').value">Generate</button>
      </div>
    </div>
  </div>
</div>

</div>