config/routes.rb
Rails.application.routes.draw do
  get '/public_recipes', to:"public_recipes#index"
  resources :recipes
  get '/general_shopping_list', to: "recipes#general_shopping_list"
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root "public_recipes#index"
  resources :recipes, only: [:index, :show, :new, :create] do
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :inventories, only: [:index, :show, :new, :create, :destroy] do
    resources :inventory_foods, only: [:new, :create, :destroy]
  end
  resources :foods, only: [:new, :create, :index, :show, :destroy]
  get '/shopping_list', to: 'shopping_list#index', as: :shopping_list, recipe_id: /[0-9]+/, inventory_id: /[0-9]+/
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
  <div class="container-fluid container">
    <%= link_to 'Public Recipes', public_recipes_path , class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'My Recipes', recipes_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Foods", foods_path, class: 'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to "Inventories", inventories_path, class: 'nav-link'%>
        </li>
      </ul>
      <%= button_to "Sign out", destroy_user_session_path, class:"btn btn-outline-danger", :method => :delete%>
    </div>
  </div>
</nav>

app/views/layouts/_shopping_list.html.erb
<br>
<h3 style="text-align: center">Shopping List</h3>
<hr>
<% if params[:inventory_id].nil? %>
    <p style="text-align: center; margin-bottom: 90px">Shopping list not generated yet...</p>
<% else %>
<div class="d-flex justify-content-between">
  <div class="shopping-data">
    <h3>Amount of food to buy: <%= @meta_data.count %></h3>
    <h3>Recipe: <i><%= link_to @recipe.name, recipe_path(@recipe), style: "color: blue" %></i></h3>
  </div>
  <br>
  <div class="shopping-data">
    <h3>Total value of food needed: $<%= @total_price %></h3>
    <div><h3>Inventory: <i><%= link_to @inventory.name, inventory_path(@inventory), style: "color: blue" %></i></h3></div>
  </div>
</div>
  <br>
  <table id = "customers" class="table table-striped table-dark">
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>price</th>
      </tr>
    </thead>
    <tbody>
      <% @meta_data.each do |item| %>
        <tr>
          <td><%= item[1]  %></td>
          <td><%= RecipeFood.find_by(food_id: item[0]).quantity %> <%= item[2] %></td>
          <td>$<%= RecipeFood.find_by(food_id: item[0]).quantity * item[3]  %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeAppRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <% if notice && notice.empty? %>
        <div class="alert alert-success" role="alert">
          <p class="notice"><%= notice %></p>
        </div>
      <% elsif alert && alert.empty?  %>
        <div class="alert alert-danger" role="alert">
          <p class="alert"><%= alert %></p>
        </div>
      <% end %>
    </div>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
</html>